services:
  db:
    image: mysql:8.0
    container_name: toyland_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: toyland_db
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

  backend:
    build: ./backend
    container_name: toyland_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=toyland_db
      - DB_USER=root
      - DB_PASSWORD=123456
    command: >
      sh -c "until nc -z db 3306; do echo 'Waiting for MySQL...'; sleep 2; done &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    container_name: toyland_frontend
    ports:
      - "3000:80"   # map host:container (nginx serve บน 80)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  db_data:
