version: '3.8'

services:
  backend:
    build: ./backend
    container_name: toyland_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=toyland_db
      - DB_USER=root
      - DB_PASSWORD=123456

  frontend:
    build: ./frontend
    container_name: toyland_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  db:
    image: mysql:8.0
    container_name: toyland_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: toyland_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
